
var a;a||(a=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},a),ba=(b,c)=>{throw c;},m="",n;m=self.location.href;m=0!==m.indexOf("blob:")?m.substr(0,m.replace(/[?#].*/,"").lastIndexOf("/")+1):"";n=b=>{var c=new XMLHttpRequest;c.open("GET",b,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)};var ca=a.print||console.log.bind(console),q=a.printErr||console.warn.bind(console);Object.assign(a,aa);aa=null;a.quit&&(ba=a.quit);var r;
a.wasmBinary&&(r=a.wasmBinary);var noExitRuntime=a.noExitRuntime||!0;"object"!=typeof WebAssembly&&t("no native wasm support detected");var ea,u=!1,x,z,A,fa=[],ha=[],ia=[],B=!1;function ja(){var b=a.preRun.shift();fa.unshift(b)}var C=0,D=null,E=null;function t(b){if(a.onAbort)a.onAbort(b);b="Aborted("+b+")";q(b);u=!0;throw new WebAssembly.RuntimeError(b+". Build with -sASSERTIONS for more info.");}function ka(){return F.startsWith("data:application/octet-stream;base64,")}var F;F="solver.wasm";
if(!ka()){var la=F;F=a.locateFile?a.locateFile(la,m):m+la}function ma(){var b=F;try{if(b==F&&r)return new Uint8Array(r);if(n)return n(b);throw"both async and sync fetching of the wasm failed";}catch(c){t(c)}}function na(){return r||"function"!=typeof fetch?Promise.resolve().then(function(){return ma()}):fetch(F,{credentials:"same-origin"}).then(function(b){if(!b.ok)throw"failed to load wasm binary file at '"+F+"'";return b.arrayBuffer()}).catch(function(){return ma()})}
function G(b){for(;0<b.length;)b.shift()(a)}
function oa(b,c){H=b;J=c;if(K)if(L||(L=!0),0==b)M=function(){var e=Math.max(0,pa+c-qa())|0;setTimeout(N,e)};else if(1==b)M=function(){ra(N)};else if(2==b){if("undefined"==typeof setImmediate){var f=[];addEventListener("message",e=>{if("setimmediate"===e.data||"setimmediate"===e.data.target)e.stopPropagation(),f.shift()()},!0);setImmediate=function(e){f.push(e);void 0===a.setImmediates&&(a.setImmediates=[]);a.setImmediates.push(e);postMessage({target:"setimmediate"})}}M=function(){setImmediate(N)}}}
var qa;qa=()=>performance.now();
function sa(b){!K||t("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");K=b;var c=O;L=!1;N=function(){if(!u)if(0<ta.length){var f=Date.now(),e=ta.shift();e.D(e.v);if(P){var d=P,g=0==d%1?d-1:Math.floor(d);P=e.A?g:(8*d+(g+.5))/9}ca('main loop blocker "'+e.name+'" took '+(Date.now()-f)+" ms");a.setStatus&&(f=a.statusMessage||"Please wait...",e=P,d=ua.C,e?e<d?a.setStatus(f+
" ("+(d-e)+"/"+d+")"):a.setStatus(f):a.setStatus(""));c<O||setTimeout(N,0)}else c<O||(va=va+1|0,1==H&&1<J&&0!=va%J?M():(0==H&&(pa=qa()),u||a.preMainLoop&&!1===a.preMainLoop()||(wa(b),a.postMainLoop&&a.postMainLoop()),c<O||("object"==typeof SDL&&SDL.audio&&SDL.audio.o&&SDL.audio.o(),M())))}}function wa(b){if(!u)try{b()}catch(c){"unwind"!=c&&ba(1,c)}}function xa(b){setTimeout(function(){wa(b)},1E4)}function ya(b){Q||(Q={});Q[b]||(Q[b]=1,q(b))}
var Q,L=!1,M=null,O=0,K=null,H=0,J=0,va=0,ta=[],ua={},pa,N,P,R=!1,za=!1,Aa=[];
function Ba(){function b(){za=document.pointerLockElement===a.canvas||document.mozPointerLockElement===a.canvas||document.webkitPointerLockElement===a.canvas||document.msPointerLockElement===a.canvas}a.preloadPlugins||(a.preloadPlugins=[]);if(!Ca){Ca=!0;try{S=!0}catch(f){S=!1,q("warning: no blob constructor, cannot create blobs with mimetypes")}Da="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:S?null:q("warning: no BlobBuilder");T="undefined"!=
typeof window?window.URL?window.URL:window.webkitURL:void 0;a.l||"undefined"!=typeof T||(q("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),a.l=!0);a.preloadPlugins.push({canHandle:function(f){return!a.l&&/\.(jpg|jpeg|png|bmp)$/i.test(f)},handle:function(f,e,d,g){var h=null;if(S)try{h=new Blob([f],{type:Ea(e)}),h.size!==f.length&&(h=new Blob([(new Uint8Array(f)).buffer],{type:Ea(e)}))}catch(p){ya("Blob constructor present but fails: "+
p+"; falling back to blob builder")}h||(h=new Da,h.append((new Uint8Array(f)).buffer),h=h.getBlob());var k=T.createObjectURL(h),l=new Image;l.onload=()=>{l.complete||t("Image "+e+" could not be decoded");var p=document.createElement("canvas");p.width=l.width;p.height=l.height;p.getContext("2d").drawImage(l,0,0);T.revokeObjectURL(k);d&&d(f)};l.onerror=()=>{ca("Image "+k+" could not be decoded");g&&g()};l.src=k}});a.preloadPlugins.push({canHandle:function(f){return!a.H&&f.substr(-4)in{".ogg":1,".wav":1,
".mp3":1}},handle:function(f,e,d,g){function h(){l||(l=!0,d&&d(f))}function k(){l||(l=!0,new Audio,g&&g())}var l=!1;if(S){try{var p=new Blob([f],{type:Ea(e)})}catch(v){return k()}p=T.createObjectURL(p);var w=new Audio;w.addEventListener("canplaythrough",()=>h(w),!1);w.onerror=function(){if(!l){q("warning: browser could not fully decode audio "+e+", trying slower base64 approach");for(var v="",I=0,y=0,da=0;da<f.length;da++)for(I=I<<8|f[da],y+=8;6<=y;){var La=I>>y-6&63;y-=6;v+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[La]}2==
y?(v+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(I&3)<<4],v+="=="):4==y&&(v+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(I&15)<<2],v+="=");w.src="data:audio/x-"+e.substr(-3)+";base64,"+v;h(w)}};w.src=p;xa(function(){h(w)})}else return k()}});var c=a.canvas;c&&(c.requestPointerLock=c.requestPointerLock||c.mozRequestPointerLock||c.webkitRequestPointerLock||c.msRequestPointerLock||(()=>{}),c.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||
document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),c.exitPointerLock=c.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",b,!1),document.addEventListener("mozpointerlockchange",b,!1),document.addEventListener("webkitpointerlockchange",b,!1),document.addEventListener("mspointerlockchange",b,!1),a.elementPointerLock&&c.addEventListener("click",f=>{!za&&a.canvas.requestPointerLock&&(a.canvas.requestPointerLock(),f.preventDefault())},!1))}}
function Fa(b,c,f,e){if(c&&a.j&&b==a.canvas)return a.j;var d;if(c){var g={antialias:!1,alpha:!1,F:1};if(e)for(var h in e)g[h]=e[h];if("undefined"!=typeof GL&&(d=GL.B(b,g)))var k=GL.getContext(d).u}else k=b.getContext("2d");if(!k)return null;f&&(c||"undefined"==typeof GLctx||t("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),a.j=k,c&&GL.G(d),a.I=c,Aa.forEach(function(l){l()}),Ba());return k}var Ga=!1,U=void 0,V=void 0;
function Ha(b,c){function f(){R=!1;var g=e.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(e.exitFullscreen=Ia,U&&e.requestPointerLock(),R=!0,V?("undefined"!=typeof SDL&&(z[SDL.screen>>2]=A[SDL.screen>>2]|8388608),W(a.canvas),Ja()):W(e)):(g.parentNode.insertBefore(e,g),g.parentNode.removeChild(g),V?("undefined"!=typeof SDL&&(z[SDL.screen>>2]=A[SDL.screen>>2]&-8388609),
W(a.canvas),Ja()):W(e));if(a.onFullScreen)a.onFullScreen(R);if(a.onFullscreen)a.onFullscreen(R)}U=b;V=c;"undefined"==typeof U&&(U=!0);"undefined"==typeof V&&(V=!1);var e=a.canvas;Ga||(Ga=!0,document.addEventListener("fullscreenchange",f,!1),document.addEventListener("mozfullscreenchange",f,!1),document.addEventListener("webkitfullscreenchange",f,!1),document.addEventListener("MSFullscreenChange",f,!1));var d=document.createElement("div");e.parentNode.insertBefore(d,e);d.appendChild(e);d.requestFullscreen=
d.requestFullscreen||d.mozRequestFullScreen||d.msRequestFullscreen||(d.webkitRequestFullscreen?()=>d.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(d.webkitRequestFullScreen?()=>d.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);d.requestFullscreen()}function Ia(){if(!R)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var X=0;
function ra(b){if("function"==typeof requestAnimationFrame)requestAnimationFrame(b);else{var c=Date.now();if(0===X)X=c+1E3/60;else for(;c+2>=X;)X+=1E3/60;setTimeout(b,Math.max(X-c,0))}}function Ea(b){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[b.substr(b.lastIndexOf(".")+1)]}var Ka=[];function Ja(){var b=a.canvas;Ka.forEach(function(c){c(b.width,b.height)})}
function W(b,c,f){c&&f?(b.s=c,b.m=f):(c=b.s,f=b.m);var e=c,d=f;a.forcedAspectRatio&&0<a.forcedAspectRatio&&(e/d<a.forcedAspectRatio?e=Math.round(d*a.forcedAspectRatio):d=Math.round(e/a.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===b.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/e,screen.height/d);e=Math.round(e*g);d=Math.round(d*g)}V?
(b.width!=e&&(b.width=e),b.height!=d&&(b.height=d),"undefined"!=typeof b.style&&(b.style.removeProperty("width"),b.style.removeProperty("height"))):(b.width!=c&&(b.width=c),b.height!=f&&(b.height=f),"undefined"!=typeof b.style&&(e!=c||d!=f?(b.style.setProperty("width",e+"px","important"),b.style.setProperty("height",d+"px","important")):(b.style.removeProperty("width"),b.style.removeProperty("height"))))}var Ca,S,Da,T;a.requestFullscreen=function(b,c){Ha(b,c)};a.requestAnimationFrame=function(b){ra(b)};
a.setCanvasSize=function(b,c,f){W(a.canvas,b,c);f||Ja()};a.pauseMainLoop=function(){M=null;O++};a.resumeMainLoop=function(){O++;var b=H,c=J,f=K;K=null;sa(f);oa(b,c);M()};a.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};a.createContext=function(b,c,f,e){return Fa(b,c,f,e)};
var Na={a:function(){t("OOM")},b:function(b,c){if(Y)throw"already responded with final response!";Y=!0;c={callbackId:Ma,finalResponse:!0,data:b?new Uint8Array(x.subarray(b,b+c)):0};b?postMessage(c,[c.data.buffer]):postMessage(c)},c:function(b,c){if(Y)throw"already responded with final response!";c={callbackId:Ma,finalResponse:!1,data:b?new Uint8Array(x.subarray(b,b+c)):0};b?postMessage(c,[c.data.buffer]):postMessage(c)}};
(function(){function b(d){a.asm=d.exports;ea=a.asm.d;d=ea.buffer;a.HEAP8=new Int8Array(d);a.HEAP16=new Int16Array(d);a.HEAP32=z=new Int32Array(d);a.HEAPU8=x=new Uint8Array(d);a.HEAPU16=new Uint16Array(d);a.HEAPU32=A=new Uint32Array(d);a.HEAPF32=new Float32Array(d);a.HEAPF64=new Float64Array(d);ha.unshift(a.asm.e);C--;a.monitorRunDependencies&&a.monitorRunDependencies(C);0==C&&(null!==D&&(clearInterval(D),D=null),E&&(d=E,E=null,d()))}function c(d){b(d.instance)}function f(d){return na().then(function(g){return WebAssembly.instantiate(g,
e)}).then(function(g){return g}).then(d,function(g){q("failed to asynchronously prepare wasm: "+g);t(g)})}var e={a:Na};C++;a.monitorRunDependencies&&a.monitorRunDependencies(C);if(a.instantiateWasm)try{return a.instantiateWasm(e,b)}catch(d){return q("Module.instantiateWasm callback failed with error: "+d),!1}(function(){return r||"function"!=typeof WebAssembly.instantiateStreaming||ka()||"function"!=typeof fetch?f(c):fetch(F,{credentials:"same-origin"}).then(function(d){return WebAssembly.instantiateStreaming(d,
e).then(c,function(g){q("wasm streaming compile failed: "+g);q("falling back to ArrayBuffer instantiation");return f(c)})})})();return{}})();a.___wasm_call_ctors=function(){return(a.___wasm_call_ctors=a.asm.e).apply(null,arguments)};a._initcard=function(){return(a._initcard=a.asm.f).apply(null,arguments)};a._solve=function(){return(a._solve=a.asm.g).apply(null,arguments)};
var Oa=a._malloc=function(){return(Oa=a._malloc=a.asm.h).apply(null,arguments)},Pa=a._free=function(){return(Pa=a._free=a.asm.i).apply(null,arguments)},Z;E=function Qa(){Z||Ra();Z||(E=Qa)};
function Ra(){function b(){if(!Z&&(Z=!0,a.calledRun=!0,!u)){B=!0;G(ha);if(a.onRuntimeInitialized)a.onRuntimeInitialized();if(a.postRun)for("function"==typeof a.postRun&&(a.postRun=[a.postRun]);a.postRun.length;){var c=a.postRun.shift();ia.unshift(c)}G(ia)}}if(!(0<C)){if(a.preRun)for("function"==typeof a.preRun&&(a.preRun=[a.preRun]);a.preRun.length;)ja();G(fa);0<C||(a.setStatus?(a.setStatus("Running..."),setTimeout(function(){setTimeout(function(){a.setStatus("")},1);b()},1)):b())}}
if(a.preInit)for("function"==typeof a.preInit&&(a.preInit=[a.preInit]);0<a.preInit.length;)a.preInit.pop()();Ra();var Y=!1,Ma=-1;
(function(){function b(){if(f&&B){var g=f;f=null;g.forEach(function(h){onmessage(h)})}}function c(){b();f&&setTimeout(c,100)}var f=null,e=0,d=0;onmessage=g=>{if(B){b();var h=a["_"+g.data.funcName];if(!h)throw"invalid worker function to call: "+g.data.funcName;var k=g.data.data;if(k){k.byteLength||(k=new Uint8Array(k));if(!e||d<k.length)e&&Pa(e),d=k.length,e=Oa(k.length);x.set(k,e)}Y=!1;Ma=g.data.callbackId;k?h(e,k.length):h(0,0)}else f||(f=[],setTimeout(c,100)),f.push(g)}})();
