name = "seahaven"
version = "0.1.0"
defaultTargets = ["seahaven"]

[[lean_lib]]
name = "Seahaven"

[[lean_exe]]
name = "seahaven"
root = "Main"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "7d81886827b128d49d35b5209cae731d2383f7b7"
